transport_conf {
    communication_mode {
        same_proc: INTRA
        diff_proc: SHM
        diff_host: RTPS
    }
}

run_mode_conf {
    run_mode: MODE_REALITY
    clock_mode: MODE_CYBER
}

scheduler_conf {
    routine_num: 100
    default_proc_num: 16
}
