name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install
      run: sudo bash scripts/deps/install_bazel.sh
    - name: make
      run: bazel build //cyber
    - name: test
      run: |
        bazel test \
          //cyber/message/... \
          //cyber/transport/rtps:rtps_test \
          //cyber/transport/integration_test:rtps_transceiver_test \
          //cyber/examples/integration_test:examples_regression_tests
